import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import Package from '../../../assets/Guarentee/Package.svg';
import Trophy from '../../../assets/Guarentee/Trophy.svg';
import Card from '../../../assets/Guarentee/CreditCard.svg';
import Headphone from '../../../assets/Guarentee/Headphones.svg';
import Line from '../../../assets/Guarentee/Line 4.svg';
const Guarantee = () => {
    return (_jsx("div", { className: 'relative z-10 bg-white  p-4 text-black max-w-screen-xl mx-auto px-4  flex', children: _jsxs("div", { className: 'flex flex-row flex-wrap gap-12 sm:p-8 sm:h-100 sm:justifiy-center sm:border-2  lg:border-2 lg:border-solid \n       border-gray-200 lg:h-25 lg:w-full lg:p-2 lg:items-center lg:justify-evenly', children: [_jsxs("div", { className: 'bg-white p-1 gap-5 lg:w-1/5 sm:w-1/2 flex lg:items-center lg:justify-between', children: [_jsx("div", { children: _jsx("img", { src: Package, alt: "" }) }), _jsxs("div", { className: '', children: [_jsx("h1", { children: "FAST DELIVERY" }), _jsx("p", { className: 'text-gray-400', children: "Delivery in 24/7" })] }), _jsx("div", { className: 'sm:hidden lg:visible', children: _jsx("img", { src: Line, alt: "", className: '' }) })] }), _jsxs("div", { className: 'bg-white p-1 gap-5 lg:w-1/5 sm:w-1/2  flex lg:items-center lg:justify-between', children: [_jsx("div", { children: _jsx("img", { src: Trophy, alt: "sm:hidden" }) }), _jsxs("div", { children: [_jsx("h1", { children: "24 HOURS RETURN" }), _jsx("p", { className: 'text-gray-400', children: "100% Money back Guarentee" })] }), _jsx("div", { children: _jsx("img", { src: Line, alt: " sm:hidden" }) })] }), _jsx("div", { children: _jsx("img", { src: Line, alt: "", className: 'sm:hidden' }) }), _jsxs("div", { className: 'bg-white p-1 lg:w-1/5 sm:w-1/2 gap-5 flex lg:items-center lg:justify-between', children: [_jsx("div", { children: _jsx("img", { src: Card, alt: "" }) }), _jsxs("div", { children: [_jsx("h1", { children: "SECURE PAYMENT" }), _jsx("p", { className: 'text-gray-400', children: "Your money is safe" })] })] }), _jsx("div", { children: _jsx("img", { src: Line, alt: "sm:hidden" }) }), _jsxs("div", { className: 'bg-white p-1 lg:w-1/5 sm:w-1/2 gap-5 flex lg:items-center lg:justify-between', children: [_jsx("div", { children: _jsx("img", { src: Headphone, alt: "" }) }), _jsxs("div", { children: [_jsx("h1", { children: "SUPPORT 24/7" }), _jsx("p", { className: 'text-gray-400', children: "Live contact/message " })] })] })] }) }));
};
export default Guarantee;
