import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import Package from '../../../assets/Guarentee/Package.svg';
import Trophy from '../../../assets/Guarentee/Trophy.svg';
import Card from '../../../assets/Guarentee/CreditCard.svg';
import Headphone from '../../../assets/Guarentee/Headphones.svg';
const Guarantee = () => {
    return (_jsx("div", { className: 'relative z-10 bg-white p-4 text-black max-w-screen-xl mx-auto flex text-center lg:text-left', children: _jsxs("div", { className: 'min-h-30 lg:border-gray-200 lg:w-full lg:h-full lg:flex lg:flex-row lg:flex-1 lg:justify-between \n          w-full h-auto flex flex-col justify-between items-center lg:border-2 border-gray-200', children: [_jsxs("div", { className: 'flex-1 flex justify-center flex-col lg:flex-row gap-2 items-center border-2 p-2 border-gray-200 w-full border-b-0 lg:border-none ', children: [_jsx("div", { children: _jsx("img", { src: Package, alt: "" }) }), _jsxs("div", { className: '', children: [_jsx("h1", { className: 'text-sm', children: "FAST DELIVERY" }), _jsx("p", { className: 'text-gray-400 text-sm', children: "Delivery in 24/7" })] })] }), _jsx("div", { className: 'hidden lg:block h-14 w-[2px] rounded-full mx-2 bg-gray-100' }), _jsxs("div", { className: 'flex-1 flex justify-center flex-col lg:flex-row gap-2 items-center border-2 p-2 border-gray-200 w-full border-b-0 lg:border-none ', children: [_jsx("div", { children: _jsx("img", { src: Trophy, alt: "" }) }), _jsxs("div", { children: [_jsx("h1", { className: 'text-sm', children: "24 HOURS RETURN" }), _jsx("p", { className: 'text-gray-400 text-sm', children: "100% Money back Guarentee" })] })] }), _jsx("div", { className: 'hidden lg:block h-14 w-[2px] rounded-full mx-2 bg-gray-100' }), _jsxs("div", { className: 'flex-1 flex justify-center flex-col lg:flex-row gap-2 items-center border-2 p-2 border-gray-200 w-full border-b-0 lg:border-none ', children: [_jsx("div", { children: _jsx("img", { src: Card, alt: "" }) }), _jsxs("div", { children: [_jsx("h1", { className: 'text-sm', children: "SECURE PAYMENT" }), _jsx("p", { className: 'text-gray-400 text-sm', children: "Your money is safe" })] })] }), _jsx("div", { className: 'hidden lg:block h-14 w-[2px] rounded-full mx-2 bg-gray-100' }), _jsxs("div", { className: 'flex-1 flex justify-center flex-col lg:flex-row gap-2 items-center border-2 p-2 border-gray-200 w-full lg:border-none ', children: [_jsx("div", { children: _jsx("img", { src: Headphone, alt: "" }) }), _jsxs("div", { children: [_jsx("h1", { className: 'text-sm', children: "SUPPORT 24/7" }), _jsx("p", { className: 'text-gray-400 text-sm', children: "Live contact/message " })] })] })] }) }));
};
export default Guarantee;
