import { jsx as _jsx, jsxs as _jsxs, Fragment as _Fragment } from "react/jsx-runtime";
import IMAC from "../../../assets/misc/IMAC.png";
import Footer from "../../../Components/HomePage/Footer/Footer";
import BlackFriday from "../../../Components/HomePage/BlackFriday/BlackFriday";
import Header from "../../../Components/HomePage/Header/Header";
import Categories from "../../../Components/HomePage/Categories/Categories";
import ComparePageProductComponent from "./navComparePageProductComponent";
const ComparePage = () => {
    return (_jsxs(_Fragment, { children: [_jsx(BlackFriday, {}), _jsx(Header, {}), _jsx(Categories, {}), _jsx("div", { className: "mx-auto max-w-screen-xl my-20 h-220 px-4", children: _jsxs("div", { className: "grid grid-cols-4 grid-rows-1 gap-4", children: [" ", _jsxs("div", { className: "flex  flex-row justify-evenly", children: [_jsx("div", { className: "border-2 h-181 w-200 border-gray-200", children: _jsx("div", { className: " flex", children: _jsxs("div", { className: "mt-4", children: [_jsx("div", { className: "bg-gray-100 p-2", children: " " }), _jsx("div", { className: "p-2", children: _jsx("h1", { children: "Customer Feedback:" }) }), _jsx("div", { className: "bg-gray-100 p-2", children: _jsx("h1", { children: "Price:" }) }), _jsx("div", { className: "p-2", children: _jsx("h1", { children: "Sold By:" }) }), _jsx("div", { className: "bg-gray-100 p-2", children: _jsx("h1", { children: "Brand:" }) }), _jsx("div", { className: "p-2", children: _jsx("h1", { children: "Model:" }) }), _jsx("div", { className: "bg-gray-100 p-2", children: _jsx("h1", { children: "Stock Status:" }) }), _jsx("div", { className: "p-2", children: _jsx("h1", { children: "Size:" }) }), _jsx("div", { className: "bg-gray-100 p-2", children: _jsx("h1", { children: "Weight:" }) })] }) }) }), _jsxs("div", { className: "", children: [" ", _jsx(ComparePageProductComponent, { imgValue: IMAC, productTitle: "Macbook Pro 2024 Edition 1TB SSD i7-7700k CPU 27 inch", reviewStars: 2, reviewCount: 245, price: 1299.00, number: undefined, soldBy: "Apple", brandName: "IMac", modelName: "Imac 2025", stockStatus: false, size: "23x4x12", weight: "14KG", emptySize: "", emptyWeight: "" })] }), _jsxs("div", { children: [" ", _jsx(ComparePageProductComponent, { imgValue: IMAC, productTitle: "Macbook Pro 2024 Edition 1TB SSD i7-7700k CPU 27 inch", reviewStars: 2, reviewCount: 245, price: 1299.00, number: undefined, soldBy: "Apple", brandName: "IMac", modelName: "Imac 2025", stockStatus: false, size: "23x4x12", weight: "14KG", emptySize: "", emptyWeight: "" })] }), _jsxs("div", { children: [" ", _jsx(ComparePageProductComponent, { imgValue: IMAC, productTitle: "Macbook Pro 2024 Edition 1TB SSD i7-7700k CPU 27 inch", reviewStars: 2, reviewCount: 245, price: 1299.00, number: undefined, soldBy: "Apple", brandName: "IMac", modelName: "Imac 2025", stockStatus: false, size: "23x4x12", weight: "14KG", emptySize: "", emptyWeight: "" })] })] })] }) }), _jsx(Footer, {})] }));
};
export default ComparePage;
