import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import Heart from "../../assets/bigBestDealProductCard/Heart.svg";
import Eyes from "../../assets/bestdeals/Eye.svg";
import Shopping from "../../assets/bestdeals/ShoppingCartSimple.svg";
import StarRating from "../../Components/RatingStars/fiveStarRating";
const bigBestDealProductCard = (props) => {
    return (_jsxs("div", { className: "lg:h-auto h-auto flex   flex-row lg:flex-col  ", children: [_jsxs("div", { className: "flex flex-col text-center font-bold  left-4 relative", children: [_jsx("div", { className: "relative  right-4 size-auto", children: _jsx("img", { src: props.imageurl, alt: "" }) }), _jsx("div", { className: "bg-yellow-400 p-2 w-20 relative bottom-65 ", children: _jsxs("h1", { children: [props.percentageOff, "% Off "] }) }), _jsx("div", { className: "bg-red-500  w-15 flex flex-col p-2   relative bottom-62", children: _jsx("h1", { className: "text-white", children: "HOT" }) })] }), _jsxs("div", { className: "flex flex-col ", children: [_jsx("div", { className: "flex flex-row ", children: _jsxs("div", { className: "flex p-2 flex-row gap-2", children: [_jsx(StarRating, { rating: 5 }), _jsxs("p", { className: "text-gray-400", children: ["(", props.reviewCount, ")"] })] }) }), _jsx("div", { className: "justify-center p-2 flex", children: _jsx("h1", { className: " text-2xl font-bold", children: "PlayStation 5 - 1tb SSD Console with Wireless Controller AUS - Version" }) }), _jsxs("div", { className: "flex p-2 gap-2 flex-row", children: [_jsxs("h1", { className: "text-green-900 text-2xl font-semibold", children: ["$", props.price] }), _jsxs("h1", { className: "text-gray-300 line-through text-2xl font-bold", children: ["$", props.discount] })] }), _jsx("div", { className: "p-2", children: _jsx("p", { children: "Games built using the PS5 development kit showcase unparalleled load times, visuals." }) }), _jsxs("div", { className: " py-5 ", children: [_jsxs("div", { className: " flex items-center   gap-4  justify-center", children: [_jsx("div", { className: "bg-yellow-400 p-4 hover:bg-yellow-200  ", children: _jsx("img", { src: Heart, alt: "" }) }), _jsx("div", { className: "bg-gray-200 hover:bg-gray-300 p-4 h-14  ", children: _jsx("button", { children: _jsxs("div", { className: "flex flex-row gap-1", children: [_jsx("img", { src: Shopping, alt: "" }), _jsx("h1", { children: "ADD TO CART" })] }) }) }), _jsx("div", { className: "bg-yellow-400 hover:bg-yellow-200 p-4 flex ", children: _jsx("img", { src: Eyes, alt: "" }) }), " "] }), " "] })] })] }));
};
export default bigBestDealProductCard;
