import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import Iphone from "../../../assets/misc/iphone.png";
import Airpods from "../../../assets/misc/airpods.webp";
import arrow from "../../../assets/LandingPage/ArrowRight.svg";
import MultiCardCarousel from "./Components/mainProductComponent";
const Landingpage = (props) => {
    return (_jsx("div", { className: "relative z-10 bg-white text-black max-w-screen-xl mx-auto px-4 p-10 mt-0 flex items-center", children: _jsxs("div", { className: "w-full grid grid-cols-1 lg:grid-cols-[70%_30%] gap-4", children: [_jsx("div", { children: _jsx(MultiCardCarousel, {}) }), _jsxs("div", { className: "flex flex-row gap-2 lg:flex-col h-auto lg:h-132 w-full", children: [_jsxs("div", { className: "bg-black text-black z-10 overflow-hidden rounded-lg transition-transform duration-500 hover:scale-105 shadow-xl h-[250px]\n            flex flex-col justify-between p-4 relative flex-1 w-full", children: [_jsx("div", { className: "flex py-5 z-20 p-2 items-center", children: _jsxs("div", { children: [_jsx("h1", { className: "text-2xl text-yellow-500 font-semibold", children: "Summer Sales" }), _jsxs("h1", { className: "text-3xl  word-break font-bold text-white", children: ["Apple iPhone ", _jsx("h1", { children: "16 256GB" })] }), _jsx("button", { className: "mt-5 z-20 bg-yellow-400 border-6 cursor-pointer border-teal-900 text-black font-semibold p-3 w-45 items-center\n                                    justify-center flex   hover:bg-yellow-200", children: _jsxs("div", { className: "flex text-lg flex-row items-center gap-4", children: [" ", "BUY NOW", _jsx("img", { src: arrow, alt: "", className: "h-5" })] }) }), _jsx("div", { className: "relative left-50 bottom-45 z-10000", children: _jsx("img", { src: Iphone, alt: "iPhone", className: "w-60 h-auto " }) })] }) }), _jsx("div", { className: "absolute top-8 right-4 w-30   text-xl h-10  bg-yellow-400 flex items-center\n                justify-center text-black  z-30 shadow-lg", children: "40% OFF" })] }), _jsx("div", { className: "flex-1 w-full bg-gray-400 text-white overflow-hidden transition-transform duration-500 hover:scale-105 rounded-lg shadow-xl h-[250px] flex flex-col justify-between p-4 relative", children: _jsxs("div", { className: "flex justify-center items-center", children: [_jsxs("div", { children: [_jsx("h1", { className: " text-3xl font-bold ", children: "Apple Airpods Pro" }), _jsx("div", { className: "text-2xl text-yellow-200 my-2", children: "$399.99" }), _jsx("button", { className: "mt-5 z-20 bg-yellow-400 border-6 cursor-pointer border-teal-900 text-black font-semibold p-3 w-45 items-center\n                justify-center flex  font-boldshadow-md hover:bg-yellow-200", children: _jsxs("div", { className: "flex text-lg flex-row items-center  gap-4", children: [" ", "BUY NOW", _jsx("img", { src: arrow, alt: "", className: "h-5" })] }) })] }), _jsx("div", { className: "w-full h-full  flex relative  left-2 top-3 justify-center items-center", children: _jsx("img", { src: Airpods, alt: "iPhone", className: "w-full  h-full " }) })] }) })] })] }) }));
};
export default Landingpage;
